RegisterNetEvent("zvrealtime:event")
AddEventHandler("zvrealtime:event", function()
    local time = os.date("!*t")
    time = os.date("*t", os.time(time) + 3600*2) --Central European Time (CET)
    -- time = os.date("*t", os.time(time) - 3600*0) --Greenwich Mean Time (GMT)
    -- time = os.date("*t", os.time(time) - 3600*4) --Eastern Time (ET)
    -- time = os.date("*t", os.time(time) - 3600*5) --Central Time (CT)
    -- time = os.date("*t", os.time(time) - 3600*6) --Mountain Time (MT)
    -- time = os.date("*t", os.time(time) - 3600*7) --Pacific Time (PT)
    TriggerClientEvent("zvrealtime:event", source, time.hour, time.min, time.sec)
end)
